site_url: https://coopdegallix.ca
search: false
backend:
  name: github
  repo: "coopdegallix/coopdegallix.ca"
  branch: pixel # Branch to update
  base_url: https://decap.coopdegallix.ca
  auth_endpoint: auth
media_folder: static/img
public_folder: /img
collections:
  - name: 'nouvelles'
    label: 'Nouvelles'
    folder: 'content/fr/nouvelles'
    create: true
    slug: '{{year}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }